### ISSUE TITLE
Does not work in build 3200

### ISSUE THREAD

**Issue by urzq** [dzhibas/SublimePrettyJson#101]
Hello,

First of all, thanks for the great work on this package.

I just installed the last version of sublime text: unregistered, Version 3.2, Build 3200.
PrettyJson does not work anymore:

- When I try to format the content of a .json file, by pressing ctrl-alt-j, or directly in sublime command launcher (ctrl-shift-p), nothing happens.
- The depth-based syntax highlight disappeared, and all my .json has the same color (yellow).

I tried to reinstall the package, but it didn't help.

Thanks :)

**Comment by cvbuelow** [comment]
Also does not work for me

**Comment by WangLiwen1994** [comment]
3207 cannot work

**Comment by TheSecEng** [comment]
Is this a continuing issue ? Does the status bar have any error codes ?

**Comment by titaniumlou** [comment]
seeing this in the console after the pretty json keyboard shortcuts don't pretty-format some json:
`reloading plugin SublimePrettyJson.PrettyJsonListeners
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/louis/Library/Application Support/Sublime Text 3/Packages/SublimePrettyJson/PrettyJsonListeners.py", line 4, in <module>
    from .PrettyJson import PrettyJsonBaseCommand
  File "/Users/louis/Library/Application Support/Sublime Text 3/Packages/SublimePrettyJson/PrettyJson.py", line 90
    replacement = f'[{join_separator.join(items)}]'
                                                  ^
SyntaxError: invalid syntax`

**Comment by TheSecEng** [comment]
Guess this is Sublime Text 4 ?

**Comment by TheSecEng** [comment]
@titaniumlou if this is ST 4, then this is definitely a bug, if this is ST 3 or below, I imagine you’ve installed it via git clone, in which case the master branch is no longer ST3 compatible, I suggest you switch to Package Control install as it will download the correct release. Which is the ST3 branch

**Comment by titaniumlou** [comment]
<img width="327" alt="Screen Shot 2020-04-26 at 9 07 44 AM" src="https://user-images.githubusercontent.com/600699/80311551-7f163b00-879d-11ea-934f-215e45af889c.png">

**Comment by titaniumlou** [comment]
Thanks for the info, I'd installed via git clone since the existing installation I had in place wasn't working (shortcuts weren't pretty-formatting json).
I removed the git clone packaged, re-installed via Package Control and things are working now...
All's well that ends well :)

**Comment by TheSecEng** [comment]
Thanks for the update!  I’ll update the Readme to include which branches support ST3.

**Comment by TheSecEng** [comment]
Updated readme with branch information
