### ISSUE TITLE
ST3 Install / Usage issues

### ISSUE THREAD

**Issue by nfritts** [dzhibas/SublimePrettyJson#119]
From a clean install of ST3

```
startup, version: 3211 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
```

I cannot find Pretty JSON to install it via Package Manager:
![image](https://user-images.githubusercontent.com/56593026/81716568-8436e380-9447-11ea-8f36-72d06ca2b5b7.png)

If I install it manually using the instructions from the main repo (`git clone https://github.com/dzhibas/SublimePrettyJson.git "Pretty JSON"`) I get the following error:

```
reloading settings Packages/Pretty JSON/Pretty JSON.sublime-settings
reloading plugin Pretty JSON.PrettyJson
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 123, in reload_plugin
    m = imp.reload(m)
  File "./python3.3/imp.py", line 276, in reload
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 853, in _load_module
  File "<frozen importlib._bootstrap>", line 980, in get_code
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\[username]\AppData\Roaming\Sublime Text 3\Packages\Pretty JSON\PrettyJson.py", line 89
    replacement = f'[{join_separator.join(items)}]'
                                                  ^
SyntaxError: invalid syntax
reloading plugin Pretty JSON.PrettyJsonListeners
```

The previous tag (1.0.0 - fb5d663) is similar:
```
reloading settings Packages/Pretty JSON/Pretty JSON.sublime-settings
reloading plugin Pretty JSON.PrettyJson
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 123, in reload_plugin
    m = imp.reload(m)
  File "./python3.3/imp.py", line 276, in reload
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 853, in _load_module
  File "<frozen importlib._bootstrap>", line 980, in get_code
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\[username]\AppData\Roaming\Sublime Text 3\Packages\Pretty JSON\PrettyJson.py", line 89
    replacement = f'[{join_separator.join(items)}]'
                                                  ^
SyntaxError: invalid syntax
reloading plugin Pretty JSON.PrettyJsonListeners
```

The tag before that ( st3-1.0.3 - 2c80b93 ) works with no issues.

I attempted to uninstall/reinstall/restart Sublime multiple times per the advice in #116 and was never able to get the plugin to work with the latest codebase.

**Comment by TheSecEng** [comment]
@nfritts Which version of Sublime Text are you running?

**Comment by nfritts** [comment]
I'm just going to blame Windows ghosts.  

Today the package does show up when I try to install it and is functional.  Yesterday it either wasn't installed or was installed but broken and didn't show up under `Package Control: List Packages`.   There could have been some other underlying issue, I didn't open the console to start debugging until after I'd manually installed.

It might be worth adding the `git checkout st3` part to the manual install instructions in the main repo readme, but for now unless I can recreate the issue again I'll just close this issue.  

Thanks for looking in to it so quickly!
