### ISSUE TITLE
AttributeError: 'PrettyJsonLintListener' object has no attribute 'view'

### ISSUE THREAD

**Issue by ratijas** [dzhibas/SublimePrettyJson#180]
When creating a new file and saving it, Pretty JSON fails with the following traceback in console:

```
Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python38/sublime_plugin.py", line 934, in on_post_save
    run_view_callbacks('on_post_save', view_id)
  File "/opt/sublime_text/Lib/python38/sublime_plugin.py", line 741, in run_view_callbacks
    callback(v, *args)
  File "/opt/sublime_text/Lib/python38/sublime_plugin.py", line 162, in profiler
    return event_handler(*args)
  File "/home/ratijas/.config/sublime-text/Installed Packages/Pretty JSON.sublime-package/PrettyJsonListeners.py", line 16, in on_post_save
    self.clear_phantoms()
  File "/home/ratijas/.config/sublime-text/Installed Packages/Pretty JSON.sublime-package/PrettyJson.py", line 194, in clear_phantoms
    self.phantom_set = sublime.PhantomSet(self.view, "json_errors")
AttributeError: 'PrettyJsonLintListener' object has no attribute 'view'
```

**Comment by deathaxe** [comment]
Well, this issue is clearly result of a design fault.

Event listeners mixin the `PrettyJsonBaseCommand` which is designed to be combined with a `TextCommand` and thus expects a `self.view` member to be present. The `EventListener` class however is a global event listener, which is called for all views - with `view` passed to each event hook.

https://github.com/dzhibas/SublimePrettyJson/blob/eef27b88ab5cb925d772e93f028d63beb988df48/PrettyJsonListeners.py#L9

So the method [`PrettyJsonBaseCommand.clear_phantoms()`](https://github.com/dzhibas/SublimePrettyJson/blob/eef27b88ab5cb925d772e93f028d63beb988df48/PrettyJsonListeners.py#L16) is called without a `self.view` object being present.
